spring:
  application:
    name: su-server
  main:
    allow-bean-definition-overriding: true

mybatis-plus:
  # 开启驼峰命名规则
  configuration:
    map-underscore-to-camel-case: true
    local-cache-scope: statement
  mapper-locations: classpath:/mybatis-plus/**/*.xml
  global-config:
    banner: false

logging:
  config: classpath:log4j2/log4j2-spring-${log4j-env:prod}.xml
